#!/usr/bin/env bash
# PreToolUse(Bash) quality gate for rusty-noter.
# GENERATED by claude-plugins/install-hooks.sh from ~/.claude/templates/gate-commit.sh.
# Do not hand-edit: re-run the installer instead, or your change is lost and the
# regex silently diverges from the other repos again.
#
# What it does: when Claude is about to run `git commit`, run the project's quality
# checks and DENY the commit if any fail.
#
# Two deliberate design rules, both load-bearing — keep them when you adapt this:
#
#  1. FAIL OPEN. If deps aren't installed, exit 0 and let the commit through. A gate
#     that can lock you out of your own repo on a fresh clone is worse than no gate.
#  2. MATCH `git commit` PRECISELY. The regex below matches `git commit`,
#     `git -c x=y commit` and `git -C path commit`, but NOT `git log --grep=commit`,
#     `git config --get commit.template`, `git commit-graph write` or `git commit-tree`.
#     Those last two are why the trailing guard is `(?![\w-])` and not `\b`: `\b` is
#     satisfied by the hyphen, so `commit\b` happily matched `commit-graph`. That bug
#     shipped to four repos before anyone ran the negative case.
#     If you loosen this, re-run the case table in claude-plugins/install-hooks.sh —
#     it refuses to install a template whose regex fails, which is the whole point.
#
# Wire it up in <project>/.claude/settings.json:
#
#   { "hooks": { "PreToolUse": [ { "matcher": "Bash", "hooks": [
#       { "type": "command",
#         "command": "${CLAUDE_PROJECT_DIR}/.claude/hooks/gate-commit.sh",
#         "timeout": 180 } ] } ] } }
#
# Then: chmod +x <project>/.claude/hooks/gate-commit.sh

set -uo pipefail

# Resolve the project root. Prefer the harness-provided var; fall back to walking up
# from this script (.claude/hooks/ -> project root) so the hook still works when run
# by hand or from a worktree. Never hardcode an absolute path here.
ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$ROOT" || exit 0

cmd="$(python3 -c 'import sys,json; print(json.load(sys.stdin).get("tool_input",{}).get("command",""))' 2>/dev/null || true)"
is_commit="$(printf '%s' "$cmd" | python3 -c 'import sys,re; print("yes" if re.search(r"\bgit\b(?:\s+-\S+|\s+-c\s+\S+|\s+-C\s+\S+)*\s+commit(?![\w-])", sys.stdin.read()) else "no")' 2>/dev/null || echo no)"
[ "$is_commit" = "yes" ] || exit 0

# Log inside the repo, not /tmp. `/tmp/<basename>_gate.txt` is world-writable and keyed
# on a name that is not unique: a sandbox or a second checkout of the same project writes
# the same path, and anyone can pre-create it mode 000 — every `>>"$out"` then fails, every
# check "fails", and no source change can ever clear it. Repo-local is unguessable by
# other users and naturally per-checkout. Ensure it is gitignored.
out="$ROOT/.claude/gate-last-run.log"
mkdir -p "$(dirname "$out")"
: > "$out" 2>/dev/null || out="$(mktemp -t gate-commit)"   # still fail open if unwritable
fails=""

# ---------------------------------------------------------------------------
# CONFIG 1 — readiness probe (fail open)
# Exit 0 here if the toolchain isn't installed.
#
# Probe EVERY binary the checks below actually invoke — not one representative.
# `[ -d node_modules ]` passes on an interrupted `npm i` that installed no bins, and a
# partial `uv sync` leaves .venv/bin/ruff without black or mypy. The checks then fail
# because the tools are MISSING, the gate denies the commit, and the reason string says
# "black mypy failed" — sending you hunting for formatting errors that do not exist.
# Partial install states are the common case, not the rare one.
# ---------------------------------------------------------------------------
command -v swift >/dev/null 2>&1 || exit 0
# The SPM packages carry the suite; a sparse checkout or a worktree can lack them, and
# `swift test --package-path` on a missing dir is a chdir error, not a test failure.
[ -f "$ROOT/Packages/NoterCore/Package.swift" ]   || exit 0
[ -f "$ROOT/Packages/NoterEditor/Package.swift" ] || exit 0
# ---------------------------------------------------------------------------
# CONFIG 2 — the checks
# One line per check. Append a short label to $fails on failure; that label is what
# gets shown to Claude, so keep it recognizable. Keep the whole suite under ~30s —
# this runs on every commit, and a slow gate trains you to work around it.
# ---------------------------------------------------------------------------
# App/ has no test target yet (see CLAUDE.md backlog) — the SPM packages carry the suite.
swift test --package-path "$ROOT/Packages/NoterCore"   >>"$out" 2>&1 || fails="${fails}NoterCore "
swift test --package-path "$ROOT/Packages/NoterEditor" >>"$out" 2>&1 || fails="${fails}NoterEditor "
# ---------------------------------------------------------------------------

if [ -n "$fails" ]; then
  FAILS="$fails" OUT="$out" python3 -c 'import json,os; print(json.dumps({"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Commit blocked — quality gate failed: "+os.environ["FAILS"].strip()+". Details in "+os.environ["OUT"]+". Fix, then commit again."}}))'
  exit 0
fi
exit 0