import Testing
import Foundation
@testable import NoterCore

@Suite struct IndexWriterTests {
    let tz = TimeZone(secondsFromGMT: 7200)!

    func note(_ path: String, _ title: String, updated: String,
              type: NoteType = .note, tags: [String] = [],
              status: RecordingStatus? = nil) -> Note {
        Note(relativePath: path,
             metadata: NoteMetadata(
                title: title, type: type,
                created: Date.iso8601Local("2026-07-01T08:00:00+02:00")!,
                updated: Date.iso8601Local(updated)!,
                tags: tags, status: status),
             body: "")
    }

    @Test func rendersSortedTableWithHeader() {
        let notes = [
            note("old.md", "Old note", updated: "2026-07-10T08:00:00+02:00", tags: ["a"]),
            note("meetings/live.md", "Live standup", updated: "2026-07-13T09:00:00+02:00",
                 type: .meeting, tags: ["work"], status: .recording),
            note("new.md", "New note", updated: "2026-07-12T08:00:00+02:00")
        ]
        let rendered = IndexWriter.render(notes: notes, timeZone: tz)
        let expected = """
        # Notes Index

        Generated by Rusty Noter. Do not edit; changes are overwritten.

        | Updated | Title | Type | Tags | Path |
        |---|---|---|---|---|
        | 2026-07-13 | Live standup | meeting (recording) | work | meetings/live.md |
        | 2026-07-12 | New note | note |  | new.md |
        | 2026-07-10 | Old note | note | a | old.md |
        """
        #expect(rendered == expected + "\n")
    }

    @Test func escapesPipesInTitles() {
        let notes = [note("a.md", "Either | Or", updated: "2026-07-13T09:00:00+02:00")]
        let rendered = IndexWriter.render(notes: notes, timeZone: tz)
        #expect(rendered.contains(#"Either \| Or"#))
    }

    @Test func writeIsAtomicAndLandsAtRoot() throws {
        let vault = try makeTempVault()
        try IndexWriter.write(notes: [note("a.md", "A", updated: "2026-07-13T09:00:00+02:00")],
                              to: vault, timeZone: tz)
        let onDisk = try String(contentsOf: vault.root.appendingPathComponent("INDEX.md"),
                                encoding: .utf8)
        #expect(onDisk.hasPrefix("# Notes Index"))
    }
}
