import Foundation

public enum IndexWriter {
    public static func render(notes: [Note]) -> String {
        let sorted = notes.sorted { $0.metadata.updated > $1.metadata.updated }
        var lines: [String] = [
            "# Notes Index",
            "",
            "Generated by Rusty Noter. Do not edit; changes are overwritten.",
            "",
            "| Updated | Title | Type | Tags | Path |",
            "|---|---|---|---|---|"
        ]
        for note in sorted {
            let day = Slug.dayString(note.metadata.updated)
            let type = note.metadata.status == .recording
                ? "\(note.metadata.type.rawValue) (recording)"
                : note.metadata.type.rawValue
            let tags = note.metadata.tags.map(escapeCell).joined(separator: ", ")
            lines.append("| \(day) | \(escapeCell(note.metadata.title)) | \(type) | \(tags) | \(escapeCell(note.relativePath)) |")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    public static func write(notes: [Note], to vault: Vault) throws {
        let url = vault.root.appendingPathComponent("INDEX.md")
        try render(notes: notes).write(to: url, atomically: true, encoding: .utf8)
    }

    private static func escapeCell(_ s: String) -> String {
        s.replacingOccurrences(of: "|", with: #"\|"#)
            .replacingOccurrences(of: "\n", with: " ")
    }
}
